# Generated by Django 3.0.6 on 2020-06-10 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20200610_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_log', models.CharField(max_length=50)),
                ('apellido_log', models.CharField(max_length=50)),
                ('log', models.BooleanField()),
                ('fecha_log', models.DateTimeField(auto_now_add=True, null=True)),
                ('id_nivelL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Nivel')),
                ('id_userL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.User')),
            ],
        ),
    ]
